### ISSUE TITLE
keep_keypad_visible no longer working

### ISSUE THREAD

**Issue by shred86** [nielsfaber/alarmo-card#16] opened 2021-11-30 03:54 UTC
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
With `keep_keypad_visible` set to `true`, the keypad should be visible when the system is disarmed.

### Actual behavior
The keypad is not visible when the system is disarmed. It does show up when the system is armed. This is the case on my iPad (Safari), iPhone (Home Assistant app) and two Amazon Fire HD 8s (Fully Kiosk).

### Steps to Reproduce
Update to the latest Alarmo Card.

**Comment by nielsfaber** [comment] 2021-11-30 05:41
Duplicate of #14

**Closed by nielsfaber** 2021-11-30 05:41 UTC
Labels: bug
